#http://localhost:8761  eureka server界面
server:
    port: 7001

eureka:
    #默认情况下erureka server也是一个eureka client ,必须要指定一个 server
    client:
        #通过fetch-registry：false和register-with-eureka：false来表明自己是一个eureka server
        fetch-registry: false
        register-with-eureka: false
        service-url:
            defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    instance:
        hostname: localhost

spring:
    application:
        name: wulang-eureka-server
